routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search');


Route::group(['namespace' => 'Panel', 'middleware' => ['auth:web', 'checkAdmin'], 'prefix' => 'panel'], function () {
    Route::get('/', 'PanelController@index')->name('panel');

    //podcast
    Route::post('podcast/accept/{podcast_id}', 'SoundController@accept')->name('podcast.accept')->middleware('can:podcast');
    Route::post('podcast/unAccept/{podcast_id}', 'SoundController@unAccept')->name('podcast.unAccept')->middleware('can:podcast');
    Route::post('upload-image' , 'SoundController@uploadImageSubject');

    Route::resource('podcast', 'SoundController')->middleware('can:podcast');


    //podcast-category
    Route::resource('category', 'SoundCategoryController')->middleware('can:podcast')->names('panelCategory');


    //comment
    Route::post('comment/accept/{comment_id}', 'CommentController@accept')->name('comment.accept')->middleware('can:comment');
    Route::post('comment/unAccept/{comment_id}', 'CommentController@unAccept')->name('comment.unAccept')->middleware('can:comment');
    Route::resource('comment', 'CommentController')->middleware('can:comment');

    //user
    Route::post('user/accept/{user_id}', 'UserController@accept')->name('user.accept');
    Route::post('user/unAccept/{user_id}', 'UserController@unAccept')->name('user.unAccept');
    Route::resource('user', 'UserController');

    //admin
    Route::resource('admin/role', 'RoleController')->middleware('can:admin-role');
    Route::resource('admin/permission', 'PermissionController')->middleware('can:admin-role');
    Route::resource('admin', 'AdminController', ['parameters' => ['role' => 'user']])->middleware('can:admin-role');
    Route::resource('static-page', 'StaticPageController');

    //menu
    Route::get('menu', 'SettingController@menu')->name('menu.index');
    Route::post('menu', 'SettingController@addToMenu')->name('menu.store');
    Route::delete('menu/{menu}', 'SettingController@removeToMenu')->name('menu.destroy');

    //setting
    Route::get('public', 'SettingController@publicSetting')->name('public.index');
    Route::post('public', 'SettingController@updateSetting')->name('public.store');

    //slider
    Route::resource('slider', 'SliderController');
    Route::resource('sliderPic', 'SliderPicController');

});


Route::group(['namespace' => 'Panel', 'middleware' => ['auth:web'], 'prefix' => 'user-panel'], function () {
    Route::get('/', 'PanelController@UserIndex')->name('user-panel.index');
    Route::get('profile', 'PanelController@UserProfile')->name('user-panel.profile');
    Route::patch('profile', 'PanelController@updateProfile')->name('profile.update');
    Route::get('upload', 'PanelController@UserUpload')->name('user-panel.upload');
    Route::post('upload', 'PanelController@UserUploadpodcast')->name('upload.podcast');
    Route::delete('upload', 'PanelController@UserDeletepodcast')->name('delete.podcast');
    Route::get('buy', 'PanelController@UserBuy')->name('user-panel.buy');

});

Auth::routes();

Route::get('podcast/{podcast_id}', 'ProductController@index');


Route::get('category/{category_id}', 'CategoryController@index')->name('category.index');

Route::resource('cart', 'CartController');
Route::group(['middleware' => ['auth:web']], function () {
    Route::get('podcast/{podcast_id}/addtocard', 'ProductController@addtocard');
    Route::get('podcast/{podcast_id}/removetocard', 'ProductController@removetocard');
});

Route::post('/product/payment', 'PaymentController@payment');
Route::get('/product/callback', 'PaymentController@callback');


Route::get('{page}', 'HomeController@staticPages');


//Route::resource('','CategoryController');
//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable=['name','location','description',];
}

app/Http/Controllers/Panel/AdminController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Role;
use App\User;
use Illuminate\Http\Request;

class AdminController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::paginate(10);
        return view('panel.admins.all',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.admins.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request , [
            'user_id' => 'required',
            'role_id' => 'required'
        ]);

//        $user = User::find($request->input('user_id'));
//        $user->update(['role'=>'admin']);
        User::find($request->input('user_id'))->roles()->sync($request->input('role_id'));
        return redirect(route('admin.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user =  User::whereId($id)->first();
        return view('panel.admins.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        User::find($request->input('user_id'))->roles()->sync($request->input('role_id'));
        return redirect(route('admin.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user =  User::whereId($id)->first();
        $user->roles()->detach();
        return redirect(route('admin.index'));

    }
}

app/Http/Controllers/Panel/ChannelController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Channel;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ChannelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function show(Channel $channel)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function edit(Channel $channel)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Channel $channel)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Channel $channel)
    {
        //
    }
}

app/Http/Controllers/Panel/CityController.php
<?php

namespace App\Http\Controllers\Panel;
use App\Http\Controllers\Controller;
use App\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        //
    }
}

app/Http/Controllers/Panel/CommentController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;

use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * accept comment in panel by admin
     **/
    public function accept($id)
    {
        $comment = Comment::where('id', $id)->first();
        $comment->update(['status' => 1]);
        return redirect()->back();

    }

    /**
     * reject comment in panel by admin
     **/
    public function unAccept($id)
    {
        $comment = Comment::where('id', $id)->first();
        $comment->update(['status' => 0]);
        return redirect()->back();
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::latest()->paginate(5);
//        return $comments;
        return view('panel.comments.all', compact('comments'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string',
            'email' => 'required|string',
            'body' => 'required|string',
        ]);
        Comment::create($request->all());
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('panel.comments.edit',compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $comment->update($request->all());
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Panel/ImageController.php
<?php

namespace App\Http\Controllers\Panel;
use App\Http\Controllers\Controller;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;


class ImageController extends Controller
{
    protected function uploadImages($file)
    {
        $year = Carbon::now()->year;
        $month = Carbon::now()->month;
        $day = Carbon::now()->day;
        $imagePath = "/upload/images/{$year}/{$month}/{$day}/";
        $filename = $file->getClientOriginalName();

        $file = $file->move(public_path($imagePath) , $filename);

        $sizes = ["300" , "600" , "900"];
        $url['images'] = $this->resize($file->getRealPath() , $sizes , $imagePath , $filename);
        $url['thumb'] = $url['images'][$sizes[0]];

        return $url;
    }

    private function resize($path , $sizes , $imagePath , $filename)
    {
        $images['original'] = $imagePath . $filename;
        foreach ($sizes as $size) {
            $images[$size] = $imagePath . "{$size}_" . $filename;

            Image::make($path)->resize($size, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path($images[$size]));
        }

        return $images;
    }
}

app/Http/Controllers/Panel/PanelController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use App\Models\Sound;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PanelController extends Controller
{
    /**
     * Show the application dashboard.
     *
     */
    public function index()
    {
        return view('panel.index');
    }
    /**
     * Show the User dashboard.
     *
     */
    public function UserIndex()
    {
        return view('userProfile.index');
    }
    public function UserProfile()
    {
        return view('userProfile.profile');
    }
    public function UserUpload()
    {
        return view('userProfile.upload');
    }

    public function UserBuy()
    {
        $payments = Payment::where('user_id','=',auth()->user()->id)->where('sucsess','=',1)->get();
        return view('userProfile.buy',compact('payments'));
    }

    public function updateProfile(Request $request)
    {
        $user = User::whereId($request->user_id)->first();
        $this->validate($request, [
            'mobile' => 'max:11|min:11',
        ]);

        if ($request->has('role')) {
            $role = $request->role;
        }
        else{
            $role = 'user';
        }

        $userUpdate = $user->update([
            'name' => $request->userName,
            'role' => $role,
            'enabled' => $request->enabled,
            'email' => $request->email,
            'mobile' => $request->mobile,
            'sex' => $request->sex,
            'address' => $request->address,
        ]);

        alert()->success('اطلاعات با موفقیت ثبت شد', ' ثبت اطلاعات')->autoclose(3500)->persistent('بستن');
        return redirect(route('user-panel.profile'));
    }
    public function UserUploadpodcast(Request $request)
    {
        $year = Carbon::now()->year;
        $month = Carbon::now()->month;
        $day = Carbon::now()->day;
        $podcastPath = "/upload/user/podcast/{$year}/{$month}/{$day}/";
        $imagePath = "/upload/user/images/{$year}/{$month}/{$day}/";


        //podcast
        $podcast = $request->file('podcast');
        $filename = $podcast->getClientOriginalName();
        $podcast = $podcast->move(public_path($podcastPath), $filename);
        $inputs['podcast'] = $podcastPath . $filename;

        $picture = $request->file('picture');
        $pictureName = $picture->getClientOriginalName();
        $picture = $picture->move(public_path($imagePath), $pictureName);
        $inputs['picture'] = $imagePath . $pictureName;


        $sound = Sound::create([
            'title' => $request->title,
            'description' => $request->description,
            'category_id' => $request->category_id,
            'picture' => $inputs['picture'],
            'podcast' => $inputs['podcast'],
            'speakers' => $request->speakers,
            'type' =>'0',   //0 free 1 cost
            'price' => '0',
            'user_id' => Auth::user()->id,
        ]);
        return redirect(route('user-panel.index'));
    }

    public function UserDeletepodcast(Request $request){
        $sound =  Sound::whereId($request->sound_id)->first();
        $sound->delete();
        return redirect(route('user-panel.index'));

    }


}

resources/views/panel/slider/all.blade.php
@extends('panel.layouts.base')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>اسلایدر ها</h2>
            <div class="btn-group">
                <a href="{{ route('slider.create') }}" class="btn btn-sm btn-danger">ایجاد اسلایدر</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>نام اسلایدر</th>
                    <th>موقعیت مکانی</th>
                    <th>توضیحات</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($sliders as $slider)
                    <tr>
                        <td>{{ $slider->name }}</td>
                        <td>{{ $slider->location }}</td>
                        <td>{{ $slider->label }}</td>
                        <td>
                            <form action="{{ route('slider.destroy'  , $slider->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <div class="btn-group btn-group-xs">
                                    {{--<a href="{{ route('role.edit' ,  $slider->id) }}"  class="btn btn-primary">ویرایش</a>--}}
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            {!! $sliders->render() !!}
        </div>
    </div>
@endsection

resources/views/panel/slider/create.blade.php
@extends('panel.layouts.base')

@section('css')
    {{--<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">--}}
    <link href="<?= Url('css/dropzone.css')?>" rel="stylesheet">
    <!-- Bootstrap time Picker -->
    {{--<link rel="stylesheet" href="<?= Url('plugins/timepicker/bootstrap-timepicker.min.css') ?>">--}}
    <!-- Persian Data Picker -->
    {{--<link rel="stylesheet" href="<?= Url('dist/css/persian-datepicker.min.css') ?>">--}}
    <!-- Select2 -->
    {{--<link rel="stylesheet" href="<?= Url('plugins/select2/select2.min.css') ?>">--}}
@endsection

@section('script')
    <script src="<?= Url('js/dropzone.js')?>"></script>

    <!-- ckeditor -->
    {{--<script src="<?= Url('plugins/ckeditor/ckeditor.js') ?>"></script>--}}
    {{--<script>--}}
    {{--CKEDITOR.replace('address', {--}}
    {{--filebrowserUploadUrl: '/panel/upload-image',--}}
    {{--filebrowserImageUploadUrl: '/panel/upload-image'--}}
    {{--});--}}
    {{--</script>--}}

    <!-- Select2 -->
    {{--<script src="<?= Url('plugins/select2/select2.full.min.js') ?>"></script>--}}
    {{--<script src="<?= Url('plugins/daterangepicker/daterangepicker.js') ?>"></script>--}}
    {{--<script src="<?= Url('dist/js/persian-date.min.js') ?>"></script>--}}
    {{--<script src="<?= Url('dist/js/persian-datepicker.min.js') ?>"></script>--}}
    {{--<script type="text/javascript">--}}
    {{--$(document).ready(function () {--}}
    {{--$(".birthday").pDatepicker({--}}
    {{--format: 'YYYY/MM/DD',--}}
    {{--});--}}
    {{--});--}}
    {{--</script>--}}
@endsection

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div style="margin-bottom: 20px" class="page-header text-center head-section">
            <h2>ثبت اسلایدر جدید</h2>
        </div>
        <form class="form-horizontal" action="{{route('slider.store')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include('layouts.errors')
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="sliderName" class="control-label">نام اسلایدر</label>
                        <input type="text" class="form-control" name="sliderName" id="sliderName"
                               placeholder="نام اسلایدر را وارد کنید" value="{{ old('sliderName') }}">
                    </div>
                </div>

                {{--<div class="col-sm-4">--}}
                {{--<div class="form-group">--}}
                {{--<label for="location" class="control-label">موقعیت مکانی</label>--}}
                {{--<input type="text" class="form-control" name="location" id="location"--}}
                {{--placeholder="ایمیل را وارد کنید"--}}
                {{--value="{{ old('location') }}">--}}
                {{--</div>--}}
                {{--</div>--}}

                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="location" class="control-label">موقعیت مکانی</label>
                        <select name="location" class="form-control select2" style="width: 100%;">
                            <option value="index" selected="selected">صفحه اصلی</option>
                        </select>
                    </div>
                </div>

            </div>


            <div class="form-group">
                <div class="col-sm-12">
                    <label for="description" class="control-label">توضیحات</label>
                    <textarea rows="2" class="form-control" name="description" id="description"
                              placeholder="توضیحات را وارد کنید">{{ old('description') }}</textarea>
                </div>
                <br>

            </div>
            <div class="form-group">
                    <div class="fallback">
                        <input name="files[]" type="file" multiple />
                    </div>
            </div>



            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-danger">ارسال</button>
                </div>
            </div>
        </form>
    </div>
@endsection